add_newline = true

format = """\
  ┌── $directory\
  $line_break\
  │ \
  $os\
  $cmd_duration\
  $git_branch \
  $git_status\
  $python\
  $status\
  $line_break\
  └ [$character](fg:#e0def4) \
  """

[cmd_duration]
format = '\[[ $duration]($style)\]'
min_time = 0
show_milliseconds = true
style = 'fg:#3e8fb0'

[os]
format = "[$symbol ]($style)"
style = "bold blue"
disabled = false

[os.symbols]
Arch = '󰣇'

[git_branch]
symbol = " "
format = '\[[$symbol$branch]($style)'
style = "fg:#ea9a97"

[git_status]
format = '[$staged$modified$renamed$deleted$untracked$ahead_behind]($style)\]'
staged = '+$count '
modified = '!$count '
renamed = '»$count '
deleted = '✘$count '
untracked = '?$count '
ahead = '${count}'
diverged = '⇕${ahead_count}${behind_count}'
behind = '${count}'
style = "fg:#ea9a97"
ignore_submodules = true
use_git_executable = true

[python]
format = '\[[Py: $venv $version]($style)\]'
style = "fg:#9ccfd8"
disabled = false

[status]
format = '[\[ $status: $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
style = "fg:#eb6f92"
disabled = false

[directory]
format = '\[[$path]($style)\]'
style = "fg:#9ccfd8"
truncation_length = 6 

[character]
format = "$symbol"
success_symbol = '\$'
error_symbol = '\$'
