# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

# ZSH Customization 
export ZSH_AUTOSUGGEST_MANUAL_REBIND=true
export ZSH_AUTOSUGGEST_STRATEGY=(history completion)


source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

bindkey '^f' autosuggest-accept
autoload -Uz compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
setopt completealiases


export ZSH="$HOME/.oh-my-zsh"
zsh_theme="robbyrussell"
plugins=(git hitchhiker)

source $ZSH/oh-my-zsh.sh
# End of lines added by compinstall

# Add deno completions to search path
if [[ ":$FPATH:" != *":/home/eduardglez/.zsh/completions:"* ]]; then export FPATH="/home/eduardglez/.zsh/completions:$FPATH"; fi
# Enable colors
autoload -U colors && colors

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000

# use the Gnu C Compiler 
#export CC=gcc
#export CXX=gcc

setopt SHARE_HISTORY
setopt autocd nomatch
unsetopt beep
bindkey -v

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/eduardglez/.zshrc'

# Segfault Core dumps
ulimit -c unlimited

# GUI settings
export DISPLAY=:0
export LIBGL_ALWAYS_INDIRECT=0

# Syntax highlight manual pages
export MANPAGER="sh -c 'sed -u -e \"s/\\x1B\[[0-9;]*m//g; s/.\\x08//g\" | bat -p -lman'"

# CUSTOM ALIAS
alias ls='eza --classify=always' 
alias ll='ls -Alh'
alias la='ls -A'
alias l='ls -CF'
alias lt="eza -lT --hyperlink --icons=always --level=3"
alias bat='bat --theme="Rose_Pine" --style="plain"'
alias cd="z"
# alias rm='_remove'
alias tp="trash-put"
alias fixmyterminalinput='stty sane'
alias top='btop'
alias ts='tmux-sessionizer'
alias grep='rg'

function makehome()
{
    export BASE=$(pwd)
    alias cx="z $BASE || z"
}
function togglecapsbtn()
{
    if test -f '/etc/systemd/system/multi-user.target.wants/keyd.service'; then
        sudo systemctl disable --now keyd
        echo "Keyd disabled"
    else
        sudo systemctl enable --now keyd
        echo "Keyd enabled"
    fi
}
function decrypt()
{
    if  [ $# -eq 0 ]; then
        echo "No file"
    else
        openssl aes-256-cbc -d -pbkdf2 -out "$1.out" -in $1
    fi

}
# cd but in the windows dir
function cdwin() {
    if [ $# -eq 0 ]; then
        cd /mnt/c/Users/Gonzalez E
    else
        cd "/mnt/c/Users/Gonzalez E/$1"
    fi
}
# create env 
function cenv(){
    python3 -m $1 .venv/
}

function devserv() {
    echo "starting..."
    . .venv/bin/activate
    export FLASK_DEBUG=1
    flask run
    echo "started"
}
# Set the PROMPT_COMMAND to call the update_ps1 function before each prompt is shown
alias vim="nvim"
alias windir="cd '/mnt/c/Users/Gonzalez E/'" 

export BASE=$(pwd)
alias cx="z $BASE || z"


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=$PATH:/usr/local/apache-maven-3.9.8/bin
export PATH=$PATH:/usr/sbin
export PATH=$PATH:/usr/local/pgsql/bin
export PATH=$PATH:/home/eduardglez/applications/gradle-8.4/bin
export PATH=$PATH:/home/eduardglez/applications/androidsdkclt/bin
export PATH=$PATH:/home/eduardglez/.keymapp
export PATH=$PATH:/home/eduardglez/.zig
export PATH=$PATH:/home/eduardglez/.local/bin
export PATH=$PATH:/home/eduardglez/.local/go/bin

export ANDROID_HOME=$HOME/android
export PATH=$ANDROID_HOME/cmdline-tools/tools/bin/:$PATH
export EDITOR="nvim"
export TERMINAL=wezterm
export REDIS_JSON_SO=/home/eduardglez/Downloads/RedisJSON/target/release/librejson.so
export PYTHONPATH=/bin/python3
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt5ct
export DEBUGINFOD_URLS="https://debuginfod.archlinux.org"
export ASAN_OPTIONS="detect_leaks=1"
export LSAN_OPTIONS="suppressions=/home/eduardglez/.config/lsan.supp"

alias chTheme='bash -c  "$(wget -qO- https://git.io/vQgMr)"'


# bun
export BUN_INSTALL="$HOME/.bun"
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	command rm -f -- "$tmp"
}

eval "$(zoxide init zsh)"
eval "$(direnv hook zsh)"
eval "$(starship init zsh)"


figlet -c $USER"_arch" | lolcat 
fastfetch && echo && hitchhiker

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/eduardglez/opt/google-cloud-sdk/path.zsh.inc' ]; then . '/home/eduardglez/opt/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/eduardglez/opt/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/eduardglez/opt/google-cloud-sdk/completion.zsh.inc'; fi
. "/home/eduardglez/.deno/env"
